language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t froggiewalker/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true froggiewalker/docker-test npm run test
